[package]
name = "board-game"
version = "0.3.6"
authors = ["Karel Peeters <karel.peeters.leuven@gmail.com>"]
description = "A board game abstraction and generic utilities around it."
license = "MIT OR Apache-2.0"
edition = "2018"
keywords = ["board", "ai", "ataxx", "sttt"]
categories = ["algorithms", "games"]
repository = "https://github.com/KarelPeeters/board-game-rs"

[features]
default = []

[dependencies]
rand = { version = "0.8.4", features = ["small_rng"] }
itertools = "0.10.3"
decorum = { version = "0.3.1", default-features = false }
internal-iterator = "0.2.0"
num-traits = "0.2.14"
nom = "7.1.0"
rand_xoshiro = "0.6.0"
cast_trait = "0.1.2"

# TODO rayon is only used in bot_game, maybe we can move that into a separate crate?
rayon = "1.5.1"

# TODO the chess crate is heavy (and takes a long time to build, see below "temp fix"), maybe replace it with
#
chess = "3.2.0"
fnv = "1.0.7"

[target.'cfg(unix)'.dependencies]
rlimit = "0.6.2"

# temporary fix until https://github.com/jordanbray/chess/pull/67 is merged
[profile.dev.build-override]
opt-level = 3
[profile.release.build-override]
opt-level = 3
[profile.test.build-override]
opt-level = 3
